<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: my_service.proto

namespace GPBMetadata;

class MyService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xCF\x01\x0A\x10my_service.proto\x12\x09myservice\"\"\x0A\x0FUserInfoRequest\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x09\"/\x0A\x10UserInfoResponse\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x0D\x0A\x05email\x18\x02 \x01(\x092S\x0A\x09MyService\x12F\x0A\x0BGetUserInfo\x12\x1A.myservice.UserInfoRequest\x1A\x1B.myservice.UserInfoResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

